"""Type stubs for the compiled `cgg._cgg` extension module.

Signatures only. The prose lives in `cgg/__init__.py`, `crates/cgg-py/README.md`
and the Rust doc comments; a fourth copy here would just be a fourth thing to
keep in step.
"""

from __future__ import annotations

import os
from typing import Any, Literal, Sequence

__version__: str

Confidence = Literal["high", "medium", "low"]
Via = Literal[
    "direct",
    "dynamic",
    "reference",
    "external",
    "stdlib",
    "ffi",
    "descriptor",
    "framework_entry",
]

class CggError(Exception): ...

class Callable:
    @property
    def id(self) -> int: ...
    @property
    def qualified_name(self) -> str: ...
    @property
    def simple_name(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def language(self) -> str: ...
    @property
    def file(self) -> int:
        """Index into `Graph.files`, not a path."""

    @property
    def start_line(self) -> int: ...
    @property
    def end_line(self) -> int: ...
    @property
    def signature_hint(self) -> str: ...
    @property
    def visibility(self) -> str: ...
    @property
    def attributes(self) -> list[str]: ...
    @property
    def synthetic(self) -> bool: ...
    @property
    def unreferenced(self) -> Confidence | None:
        """Set if cgg found no caller. BEST EFFORT — a hypothesis, not a proof."""

class Edge:
    @property
    def src(self) -> int: ...
    @property
    def dst(self) -> int: ...
    @property
    def site_line(self) -> int: ...
    @property
    def site_byte(self) -> int: ...
    @property
    def confidence(self) -> Confidence: ...
    @property
    def via(self) -> Via: ...

class File:
    @property
    def id(self) -> int: ...
    @property
    def path(self) -> str: ...
    @property
    def language(self) -> str: ...
    @property
    def detected_via(self) -> str: ...
    @property
    def blake3(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def lines(self) -> int: ...
    @property
    def parse_status(self) -> str: ...

class Metrics:
    @property
    def files_discovered(self) -> int: ...
    @property
    def files_analyzed(self) -> int: ...
    @property
    def files_skipped(self) -> int: ...
    @property
    def files_errored(self) -> int: ...
    @property
    def callables(self) -> int: ...
    @property
    def edges(self) -> int: ...
    @property
    def cross_file_edges(self) -> int: ...
    @property
    def unresolved_calls(self) -> int: ...
    @property
    def stdlib_calls(self) -> int: ...
    @property
    def external_calls(self) -> int: ...
    @property
    def bytes_processed(self) -> int: ...
    @property
    def wall_ms(self) -> float: ...

class Graph:
    @property
    def callables(self) -> tuple[Callable, ...]: ...
    @property
    def edges(self) -> tuple[Edge, ...]: ...
    @property
    def files(self) -> tuple[File, ...]: ...
    @property
    def metrics(self) -> Metrics: ...
    @property
    def notices(self) -> list[str]: ...
    @property
    def jobs(self) -> int: ...
    def __len__(self) -> int: ...
    def to_mermaid(self) -> str: ...
    def to_json(self) -> str: ...
    def to_dot(self) -> str: ...
    def to_graphml(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def callable(self, qualified_name: str) -> Callable | None: ...
    def callers_of(self, target: Callable | str) -> list[Callable]: ...
    def callees_of(self, target: Callable | str) -> list[Callable]: ...

def analyze(
    paths: str | os.PathLike[str] | Sequence[str | os.PathLike[str]],
    *,
    filter: Sequence[str] | None = ...,
    hops: int = ...,
    max_paths: int = ...,
    fanout_cap: int = ...,
    report_unreferenced: bool = ...,
    exclude_partial: Sequence[str] | None = ...,
    exclude_glob: Sequence[str] | None = ...,
    exclude_regex: Sequence[str] | None = ...,
    lang: Sequence[str] | None = ...,
    jobs: int = ...,
    ignore_file: str | os.PathLike[str] | None = ...,
    include_external: bool = ...,
    include_stdlib: bool = ...,
    dynamic_dispatch: bool = ...,
    reference_edges: bool = ...,
    entry_nodes: bool = ...,
    include_tests: bool = ...,
    dead_code: bool = ...,
    dead_code_confidence: Confidence = ...,
    ignore_names: Sequence[str] | None = ...,
    ignore_attributes: Sequence[str] | None = ...,
    roots: str | os.PathLike[str] | None = ...,
    since: str | None = ...,
) -> Graph:
    """Raises CggError if the analysis fails, ValueError on a bad argument."""

def languages() -> list[str]: ...
