/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * An analyzed call graph.
 *
 * Holds the whole outcome behind an `Arc` and materializes JavaScript
 * values only when asked. The renderers materialize none, so
 * `toMermaid()` on a large graph does not pay to build one JS object per
 * callable first.
 */
export declare class Graph {
  /** Callables in the graph. */
  get callables(): Array<Callable>
  /** Resolved call edges. */
  get edges(): Array<Edge>
  /** Analyzed file paths, indexed by `Callable.file`. */
  get files(): Array<string>
  /** Whole-run counters. */
  get metrics(): Metrics
  /** The diagnostics the CLI would print to stderr, in order. */
  get notices(): Array<string>
  /** Worker threads the run actually used. */
  get jobs(): number
  /** Number of callables, without materializing them. */
  get callableCount(): number
  /** Render as a mermaid flowchart — what the CLI emits by default. */
  toMermaid(): string
  /**
   * Render as `cgg.graph.v1` JSON.
   *
   * Matches `cgg -t json` except for the per-run parse timings it
   * embeds (`parse_ms`, `wall_ms`), which differ between any two runs
   * of any build. `toMermaid`, `toDot` and `toGraphml` carry no
   * timings and ARE byte-identical.
   */
  toJson(): string
  /** Render as Graphviz DOT. */
  toDot(): string
  /** Render as GraphML. */
  toGraphml(): string
}

/**
 * Analyze a source tree.
 *
 * Accepts one path or several. Returns a promise: the analysis runs on
 * tokio's blocking pool via `spawn_blocking` (napi's `tokio_rt`
 * feature), not on the JS thread, so an event loop stays responsive for
 * the ~130 ms a real tree costs. Verified by counting timer ticks during
 * a run: they keep firing under `analyze` and stop under `analyzeSync`.
 *
 * ```js
 * const cgg = require("cgg-callgraphgenerator");
 * const g = await cgg.analyze("./src");
 * console.log(g.toMermaid());
 * ```
 */
export declare function analyze(paths: string | Array<string>, options?: AnalyzeOptions | undefined | null): Promise<Graph>

/**
 * Options that change the graph.
 *
 * Every field is optional and defaults to [`cgg::RunOptions`]'s default,
 * so `analyze(path)` is the whole API for the common case. Named as
 * JavaScript would name them; `napi` maps camelCase to these.
 *
 * One rename from the CLI, matching the Python module: `entryNodes: true`
 * rather than `--no-entry-nodes`. Same default; a keyword has no reason
 * to be a double negative.
 */
export interface AnalyzeOptions {
  filter?: Array<string>
  hops?: number
  maxPaths?: number
  excludePartial?: Array<string>
  excludeGlob?: Array<string>
  excludeRegex?: Array<string>
  lang?: Array<string>
  jobs?: number
  ignoreFile?: string
  includeExternal?: boolean
  includeStdlib?: boolean
  dynamicDispatch?: boolean
  referenceEdges?: boolean
  /** `true` (the default) mints `<framework-entry>` nodes. */
  entryNodes?: boolean
  includeTests?: boolean
  deadCode?: boolean
  /** `"high"` (default), `"medium"` or `"low"`. */
  deadCodeConfidence?: string
  ignoreNames?: Array<string>
  ignoreAttributes?: string
  roots?: string
  since?: string
}

/**
 * Analyze synchronously. Blocks the JS thread — prefer [`analyze`].
 *
 * Here for scripts and CLIs, where blocking is what you want and a
 * promise is ceremony.
 */
export declare function analyzeSync(paths: string | Array<string>, options?: AnalyzeOptions | undefined | null): Graph

/** One callable in the graph. */
export interface Callable {
  id: number
  qualifiedName: string
  simpleName: string
  kind: string
  language: string
  /** Index into [`Graph::files`], not a path. */
  file: number
  startLine: number
  endLine: number
  signatureHint: string
  visibility: string
  synthetic: boolean
  /**
   * Set when cgg found no caller. **Best effort** — a hypothesis, not
   * a proof.
   */
  unreferenced?: string
}

/**
 * One resolved call edge.
 *
 * Field-for-field the same as the Python module's `Edge`, deliberately:
 * two bindings over one pipeline should not describe the same graph with
 * different words.
 */
export interface Edge {
  src: number
  dst: number
  siteLine: number
  siteByte: number
  /** `"high"`, `"medium"` or `"low"`. */
  confidence: string
  /**
   * How the edge was established — `"direct"`, `"dynamic"`,
   * `"reference"`, `"external"`, `"stdlib"`, `"ffi"`, `"descriptor"`
   * or `"framework_entry"`. Filter on this to keep only edges you trust.
   */
  via: string
}

/** Every language id cgg can analyze, in registry order. */
export declare function languages(): Array<string>

/**
 * Whole-run counters. Not the post-query subgraph, so these can exceed
 * `callables.length` on a filtered run.
 */
export interface Metrics {
  filesDiscovered: number
  filesAnalyzed: number
  filesSkipped: number
  callables: number
  edges: number
  unresolvedCalls: number
  stdlibCalls: number
  externalCalls: number
  wallMs: number
}

/** The cgg version this module was built from. */
export declare function version(): string
